import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite-plus";

// https://vite.dev/config/
export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react"],
    categories: {
      correctness: "warn",
    },
    env: {
      builtin: true,
    },
    ignorePatterns: ["dist/**/*", "node_modules/**/*"],
    rules: {
      "@typescript-eslint/ban-ts-comment": "error",
      "no-array-constructor": "error",
      "@typescript-eslint/no-duplicate-enum-values": "error",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-misused-new": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-this-alias": "error",
      "@typescript-eslint/no-unnecessary-type-constraint": "error",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/no-unsafe-function-type": "error",
      "no-unused-expressions": "error",
      "no-unused-vars": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/prefer-as-const": "error",
      "@typescript-eslint/prefer-namespace-keyword": "error",
      "@typescript-eslint/triple-slash-reference": "error",
    },
    overrides: [
      {
        files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-class-members": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": "off",
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-var": "error",
          "no-with": "off",
          "prefer-const": "error",
          "prefer-rest-params": "error",
          "prefer-spread": "error",
        },
      },
      {
        files: ["**/*.md"],
        rules: {
          "markdown/fenced-code-language": "error",
          "markdown/heading-increment": "error",
          "markdown/no-duplicate-definitions": "error",
          "markdown/no-empty-definitions": "error",
          "markdown/no-empty-images": "error",
          "markdown/no-empty-links": "error",
          "markdown/no-invalid-label-refs": "error",
          "markdown/no-missing-atx-heading-space": "error",
          "markdown/no-missing-label-refs": "error",
          "markdown/no-missing-link-fragments": "error",
          "markdown/no-multiple-h1": "error",
          "markdown/no-reference-like-urls": "error",
          "markdown/no-reversed-media-syntax": "error",
          "markdown/no-space-in-emphasis": "error",
          "markdown/no-unused-definitions": "error",
          "markdown/require-alt-text": "error",
          "markdown/table-column-count": "error",
          "markdown/no-html": ["error"],
        },
        jsPlugins: ["@eslint/eslint-plugin-markdown"],
      },
      {
        files: ["**/*.html"],
        rules: {
          "@html-eslint/use-baseline": [
            "warn",
            {
              available: "widely",
            },
          ],
        },
        jsPlugins: ["@html-eslint/eslint-plugin"],
      },
      {
        files: ["**/*.{js,mjs,cjs,ts,mts,cts}"],
        rules: {
          "constructor-super": "error",
          "for-direction": "error",
          "getter-return": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-const-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-class-members": "error",
          "no-dupe-else-if": "error",
          "no-dupe-keys": "error",
          "no-duplicate-case": "error",
          "no-empty": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-func-assign": "error",
          "no-global-assign": "error",
          "no-import-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-new-native-nonconstructor": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-obj-calls": "error",
          "no-prototype-builtins": "error",
          "no-redeclare": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-setter-return": "error",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-this-before-super": "error",
          "no-undef": "error",
          "no-unexpected-multiline": "error",
          "no-unreachable": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-negation": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-with": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
        },
        env: {
          browser: true,
        },
        globals: {
          AudioWorkletGlobalScope: "readonly",
          AudioWorkletProcessor: "readonly",
          currentFrame: "readonly",
          currentTime: "readonly",
          registerProcessor: "readonly",
          sampleRate: "readonly",
          WorkletGlobalScope: "readonly",
        },
      },
      {
        files: ["**/*.css"],
        rules: {
          "css/font-family-fallbacks": "error",
          "css/no-duplicate-imports": "error",
          "css/no-duplicate-keyframe-selectors": "error",
          "css/no-empty-blocks": ["error"],
          "css/no-important": "error",
          "css/no-invalid-at-rule-placement": "error",
          "css/no-invalid-at-rules": ["error"],
          "css/no-invalid-named-grid-areas": "error",
          "css/no-invalid-properties": [
            "error",
            {
              allowUnknownVariables: true,
            },
          ],
          "css/no-unmatchable-selectors": "error",
          "css/use-baseline": [
            "warn",
            {
              available: "widely",
            },
          ],
        },
        jsPlugins: ["@eslint/eslint-plugin-css"],
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  fmt: {
    printWidth: 80,
    sortPackageJson: false,
    ignorePatterns: [],
  },
  base: "/pure-html",
  plugins: [],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  server: {
    port: 8080,
  },
  preview: {
    port: 8080,
  },
});
